### PR TITLE
Use addext, remext flags as overrides

### LINKED ISSUE #77: Lack of extensions in the core profile
Hi,

I was using https://github.com/go-gl/gl bindings and I saw that EXT_texture_filter_anisotropic is not exposed when using the core profile. I report this there, but it seems that this is glow related. I guess that this is expected behavior.

However, I don't understand a few things. Firstly, why did you remove extensions from the core profile? After reading https://www.opengl.org/wiki/Core_And_Compatibility_in_Contexts I think that extensions are not marked as deprecated, some old "core" functionality is.

So, there are 3 options: use the compability profile with all extensions included, use the compability profile with some extensions excluded as the user excludes them, and use the core profile without any extensions (I don't think that extensions included in core OpenGL should count as an extension). I don't understand why a fourth option (core+extensions) can be used.

Moreover, I think that this fourth option is the better way to go. Removing deprecated functionality (like fixed pipeline) is normally the best option, and I guess that most people will agree with me in that. However, removing all extensions from the core profile is not good at all. There are extensions that provides really useful functionality and that are implemented everywhere, see https://www.opengl.org/wiki/Ubiquitous_Extension . Using OpenGL without anisotropic filtering in 2016 seems plainly wrong to me, this extension was made in the 1999, all AAA games provides it, it is very easy to use and it improves image quality. Moreover, there is no possible good workaround to this since using texelFetch will mean an important performance loss (and implementing anisotropic filtering in a shader won't be an easy task either).

Maybe you don't want to include all extensions on the core profile by default, but at least I think that an option to include extensions should exists.

Finally, I think that this should be documented in the Readme since "remext: A regular expression describing which extensions to exclude. Empty by default, excluding nothing. Takes precedence over explicitly added regular expressions." gives the impression that all extensions are included by default on both profiles.

### PR DESCRIPTION
**Pull request by errcw**
Fixes #77.

Should be functionality-neutral for go-gl/gl but hopefully more useful for folks building custom packages.

### CODE REVIEW

**Comment by errcw** [comment]
I've reviewed this change, and I believe it's reasonable, so I'm just going to go ahead and merge it. I'm happy to revisit if there are comments post-commit.

File: main.go [hunk 1]
```diff
@@ -75,14 +75,20 @@ func generate(name string, args []string) {
 		log.Fatalln("error parsing version:", err)
 	}
 
-	addExtRegexp, err := regexp.Compile(*addext)
-	if err != nil {
-		log.Fatalln("error parsing extension inclusion regexp:", err)
+	var addExtRegexp *regexp.Regexp = nil
+	if *addext != "" {
```
Comment (shurcooL) [inline main.go]: Would the behavior change if this if statement were `if true {` instead? Or is this strictly an optimization?

I ask because in the documentation flag, there's no mention of special behavior if the flag has empty string value.

**Comment by shurcooL** [comment]
> I've reviewed this change, and I believe it's reasonable, so I'm just going to go ahead and merge it. I'm happy to revisit if there are comments post-commit.

Glad you did that, and sorry for the delay. Reviewing this PR and issue was on my "snoozed notifications" list that I kept deferring because I couldn't get around to it.

I've looked it over now, and it looks good. Just see one inline question above.

File: main.go (hunk 1 above)
Comment (errcw) [inline main.go]: If we omitted the check against "" we'd end up with a regexp of the empty string, which matches everything: https://play.golang.org/p/_t_Lw5UfxK  I figured that "empty" is a reasonably standard way to describe "unset" so I didn't clarify in the docs; I'm happy to do so if you think it'd help.

Comment (shurcooL) [inline main.go]: I see, thanks.

I think it would help.

If I am a user, and I read `glow generate -help` and it said:

```
-addext string
    	Regular expression of extensions to include (e.g., .*)
```

I would expect `-addext 'foo'` to use whatever string I give it (including empty string) as the regular expression. Or, if I worry that empty regular expression is weird, I might have to look at the source and check what it actually does.

But if we just briefly mention that the regular expression is only used if it's not empty in the flag description, I think that'd be a nice thing that would remove the need for all of the above.

We can use go generate's `-run` flag description as an example:

```
Go generate accepts one specific flag:

	-run=""
		if non-empty, specifies a regular expression to select
		directives whose full original source text (excluding
		any trailing spaces and final newline) matches the
		expression.
```

So how about something like this:

```
-addext string
    	If non-empty, regular expression of extensions to include (e.g., .*)
```

Comment (errcw) [inline main.go]: Sounds good, I updated the docs in #83

Comment (shurcooL) [inline main.go]: In #83, you updated README.md only. What about the actual flag descriptions in main.go? Did you forget about them, or leave them on purpose?

Comment (errcw) [inline main.go]: Arg, serves me right for doing this in a hurry. Created #84 to update the flag docs. This time I've learned my lesson, I'll leave it to you to review and merge.
